version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pytest coverage
      - run:
          name: Run unit tests
          command: pytest  test.py
      - run:
          name: Generate coverage report
          command: coverage run --source=. -m pytest test.py && coverage report
  deploy:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Login to Heroku
          command: echo "c044400f-b29a-4f4e-b40b-ee80106b482c" | docker login --username=_ --password-stdin registry.heroku.com
      - run:
          name: Deploy to Heroku
          command: heroku container:push web -a minesweeper-ish && heroku container:release web -a minesweeper-ish
workflows:
  build-and-test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
